import { useState, useEffect } from 'react';
import { api } from '../utils/api';

export default function ReportView() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.getReport().then(setReport).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="text-slate-400 text-center py-8">Generating intelligence report with IBM Bob AI...</div>;

  return (
    <div className="animate-fade-in space-y-3">
      <div className="glass-card p-4 glow-blue">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-white">Crime Intelligence Report</h2>
            <p className="text-xs text-slate-400">
              Generated by IBM Bob AI &middot; {report?.generated_at?.slice(0, 10) || 'Today'}
            </p>
          </div>
          <button
            onClick={() => {
              const blob = new Blob([formatReport(report)], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = 'crime_intelligence_report.txt';
              a.click();
              URL.revokeObjectURL(url);
            }}
            className="px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700"
          >
            Download Report
          </button>
        </div>
      </div>

      {report?.metadata && (
        <div className="grid grid-cols-4 gap-3">
          <MetricCard label="FIRs Analyzed" value={report.metadata.total_firs} />
          <MetricCard label="Repeat Offenders" value={report.metadata.repeat_offender_count} color="red" />
          <MetricCard label="Districts Covered" value={report.metadata.districts?.length || 0} />
          <MetricCard label="Networks Identified" value={report.metadata.patterns?.length || 0} color="amber" />
        </div>
      )}

      {report?.metadata?.crime_breakdown && (
        <div className="glass-card p-4">
          <h3 className="text-sm font-semibold text-slate-300 mb-3">Crime Breakdown</h3>
          <div className="grid grid-cols-4 gap-2">
            {Object.entries(report.metadata.crime_breakdown).sort((a, b) => b[1] - a[1]).map(([ct, count]) => (
              <div key={ct} className="bg-slate-900/50 rounded-lg p-3 text-center">
                <div className="text-xl font-bold text-white">{count}</div>
                <div className="text-xs text-slate-400 mt-0.5">{ct.replace('_', ' ')}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {report?.metadata?.patterns?.length > 0 && (
        <div className="glass-card p-4 glow-red">
          <h3 className="text-sm font-semibold text-red-400 mb-3">Identified Crime Networks</h3>
          <div className="space-y-2">
            {report.metadata.patterns.map((p, i) => (
              <div key={i} className="flex items-center gap-2 bg-red-950/20 rounded-lg px-3 py-2 border border-red-900/20">
                <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse"></span>
                <span className="text-sm text-red-300">{p}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="glass-card p-5">
        <h3 className="text-sm font-semibold text-blue-400 mb-3">Full Intelligence Report</h3>
        <div className="prose prose-invert prose-sm max-w-none">
          <pre className="text-sm text-slate-300 whitespace-pre-wrap font-sans leading-relaxed bg-slate-900/50 rounded-lg p-4 border border-slate-700">
            {report?.report || 'Report generation in progress...'}
          </pre>
        </div>
      </div>
    </div>
  );
}

function MetricCard({ label, value, color = 'blue' }) {
  const colorClass = color === 'red' ? 'text-red-400' : color === 'amber' ? 'text-amber-400' : 'text-blue-400';
  return (
    <div className="glass-card p-3 text-center">
      <div className={`text-2xl font-bold ${colorClass}`}>{value}</div>
      <div className="text-xs text-slate-500 mt-0.5">{label}</div>
    </div>
  );
}

function formatReport(report) {
  if (!report) return '';
  let text = `CRIME INTELLIGENCE REPORT\n`;
  text += `Generated: ${report.generated_at || 'Today'}\n`;
  text += `${'='.repeat(60)}\n\n`;

  if (report.metadata) {
    text += `SUMMARY\n${'-'.repeat(40)}\n`;
    text += `Total FIRs Analyzed: ${report.metadata.total_firs}\n`;
    text += `Repeat Offenders: ${report.metadata.repeat_offender_count}\n`;
    text += `Districts: ${report.metadata.districts?.join(', ')}\n`;
    text += `Crime Networks: ${report.metadata.patterns?.join(', ')}\n\n`;

    text += `CRIME BREAKDOWN\n${'-'.repeat(40)}\n`;
    Object.entries(report.metadata.crime_breakdown || {}).forEach(([ct, count]) => {
      text += `  ${ct}: ${count}\n`;
    });
    text += '\n';
  }

  text += `DETAILED ANALYSIS\n${'-'.repeat(40)}\n`;
  text += report.report || '';

  return text;
}
